from skeletons.server_skeleton import ServerSkeleton

PORT_REQREP = 5001
PORT_PUBSUB = 5002
HOST = "25.67.247.53"

OP_VALIDATEPLAYER = "VALIDATEPLAYER"
OP_MOVERIGHT = "MOVERIGHT"
OP_MOVELEFT = "MOVELEFT"
OP_ROT_R = "ROTRIGHT"
OP_ROT_L = "ROTLEFT"
OP_GETBOARD = "GETBOARD"
OP_BOARDUPDATE = "UPDATEBOARD"
OP_MATCHEXISTS = "MATCHEXISTS"
OP_DISCONNECT = "DISCONNECT"