from stubs.game_server import GameServer

HOST = "127.0.0.1"
PORT_REQREP = 5001
PORT_PUBSUB = 5002

OP_VALIDATEPLAYER = "VALIDATEPLAYER"
OP_MOVERIGHT = "MOVERIGHT"
OP_MOVELEFT = "MOVELEFT"
OP_ROT_R = "ROTRIGHT"
OP_ROT_L = "ROTLEFT"
OP_GETBOARD = "GETBOARD"
OP_BOARDUPDATE = "UPDATEBOARD"